services:
  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: agentic_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - agentic_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: agentic_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agentic_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: agentic_backend:latest
    container_name: agentic_backend
    environment:
      - DATABASE_URL=mongodb://mongo:27017/agentic_platform
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - ENVIRONMENT=development
      - DEBUG=${DEBUG}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - agentic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --workers 4
    restart: "no"

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agentic_celery_worker
    command: celery -A src.core.celery_app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=mongodb://mongo:27017/agentic_platform
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - agentic_network
    restart: "no"

  # Celery Beat
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agentic_celery_beat
    command: celery -A src.core.celery_app.celery_app beat -s /app/celerybeat-schedule --loglevel=info
    environment:
      - DATABASE_URL=mongodb://mongo:27017/agentic_platform
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
    volumes:
      - ./logs:/app/logs
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - agentic_network
    restart: "no"

  # Next.js Frontend
  nextjs_frontend:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8000 # Point to backend service
    container_name: agentic_nextjs_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api # Through nginx proxy
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - agentic_network
    restart: "no"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: agentic_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - backend
      - nextjs_frontend # Nginx now depends on the new frontend
    networks:
      - agentic_network
    restart: "no"
    command: >
      sh -c "
      rm -f /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "

volumes:
  mongo_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  agentic_network:
    driver: bridge